// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiY8b-2Tj3nlBUnbJu83L-mQRiLLMe_4Y',
    appId: '1:1011329941333:web:a01c35500832c902f879dc',
    messagingSenderId: '1011329941333',
    projectId: 'task-37175',
    authDomain: 'task-37175.firebaseapp.com',
    storageBucket: 'task-37175.firebasestorage.app',
    measurementId: 'G-502J43X7Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW8Ds8vlKfGxa1SXfu08i7iKTZuxRM6HU',
    appId: '1:1011329941333:android:9de7e6022b4ae28ef879dc',
    messagingSenderId: '1011329941333',
    projectId: 'task-37175',
    storageBucket: 'task-37175.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADRV1YjSrUouFg_CfqBdi2e8yHoASVTRQ',
    appId: '1:1011329941333:ios:9cc8f483257d2bf4f879dc',
    messagingSenderId: '1011329941333',
    projectId: 'task-37175',
    storageBucket: 'task-37175.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADRV1YjSrUouFg_CfqBdi2e8yHoASVTRQ',
    appId: '1:1011329941333:ios:9cc8f483257d2bf4f879dc',
    messagingSenderId: '1011329941333',
    projectId: 'task-37175',
    storageBucket: 'task-37175.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiY8b-2Tj3nlBUnbJu83L-mQRiLLMe_4Y',
    appId: '1:1011329941333:web:6b64e3a00466bb5df879dc',
    messagingSenderId: '1011329941333',
    projectId: 'task-37175',
    authDomain: 'task-37175.firebaseapp.com',
    storageBucket: 'task-37175.firebasestorage.app',
    measurementId: 'G-96G4SWYSFN',
  );
}
